# Generated by Django 6.0.1 on 2026-01-16 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_18_plus', models.BooleanField(default=False)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('is_preorder', models.BooleanField(default=False)),
                ('preorder_release_date', models.DateTimeField(blank=True, null=True)),
                ('is_bundle', models.BooleanField(default=False, help_text='If true, this product is composed of other variants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'SELLER'}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(help_text='e.g. Size L, Color Red', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('weight_g', models.IntegerField(default=0, help_text='Weight in grams for shipping')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text="Dynamic attributes e.g. {'color': 'red'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_bundles', to='products.productvariant')),
            ],
            options={
                'unique_together': {('bundle_product', 'variant')},
            },
        ),
    ]
