# Generated by Django 6.0.1 on 2026-01-17 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundleitem',
            options={'verbose_name': 'Paket İçeriği', 'verbose_name_plural': 'Paket İçerikleri'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Ürün Varyasyonu', 'verbose_name_plural': 'Ürün Varyasyonları'},
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='ortalama puan'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='değerlendirme sayısı'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='bundle_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product', verbose_name='paket ürün'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='miktar'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_bundles', to='products.productvariant', verbose_name='varyasyon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_18_plus',
            field=models.BooleanField(default=False, verbose_name='18+ yaş sınırı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='Eğer doğruysa, bu ürün diğer varyasyonlardan oluşur', verbose_name='paket ürün mü'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_preorder',
            field=models.BooleanField(default=False, verbose_name='ön sipariş'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ürün adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preorder_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ön sipariş çıkış tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(default=False, verbose_name='reçete gerektirir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role': 'SELLER'}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='satıcı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='kısa isim (slug)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'İnceleme Bekliyor'), ('ACTIVE', 'Aktif'), ('SUSPENDED', 'Askıya Alındı'), ('ARCHIVED', 'Arşivlendi')], default='DRAFT', max_length=20, verbose_name='durum'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='güncellenme tarihi'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text="Dinamik özellikler ör. {'renk': 'kırmızı'}", verbose_name='özellikler'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='indirim öncesi fiyat'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(help_text='ör. Beden L, Renk Kırmızı', max_length=255, verbose_name='varyasyon adı'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='fiyat'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='ürün'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='stok kodu (SKU)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='stok adedi'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='güncellenme tarihi'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight_g',
            field=models.IntegerField(default=0, help_text='Kargo için gram cinsinden ağırlık', verbose_name='ağırlık (gram)'),
        ),
    ]
