# Generated by Django 6.0.1 on 2026-01-17 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_bundleitem_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SELLER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='satıcı'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default='Standart', help_text='ör. Standart, Beden L, Kırmızı', max_length=255, verbose_name='varyasyon adı'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='görsel')),
                ('is_main', models.BooleanField(default=False, verbose_name='ana görsel mi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='ürün')),
            ],
            options={
                'verbose_name': 'Ürün Görseli',
                'verbose_name_plural': 'Ürün Görselleri',
            },
        ),
    ]
