# Generated by Django 6.0.1 on 2026-01-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_seller_alter_productvariant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='kategori adı')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, help_text='Emoji veya icon class', max_length=50, verbose_name='ikon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='sıralama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='kategori'),
        ),
    ]
